version: '3'
services:
  servizionode:
    build: ./node
    container_name: node_container
    image: servizionode
    ports:
      - 8080:8080
    networks:
      - rete
  serviziomysql:
    build: ./mysql
    container_name: mysql_container
    image: serviziomysql
    networks:
      - rete
    volumes:
      - volumesql:/var/lib/mysql
  serviziophp:
    build: ./php
    container_name: php_container
    image: serviziophp
    networks:
      - rete
networks:
  rete:
    name: rete
volumes:
  volumesql:
    name: volumesql