FROM ubuntu
RUN apt update
RUN apt install nodejs -y
RUN apt install npm -y
COPY ./app.js .
COPY ./package.json .
COPY ./views/. /views
COPY ./public/. /public
RUN npm install
EXPOSE 8080
ENTRYPOINT [ "node", "app.js" ]